const OPEN_SNACKBAR_ERROR = 'snackbar/OPEN_SNACKBAR_ERROR';
const OPEN_SNACKBAR_SUCCESS = 'snackbar/OPEN_SNACKBAR_SUCCESS';
const CLOSE_SNACKBAR_ERROR = 'snackbar/CLOSE_SNACKBAR';
const CLOSE_SNACKBAR_SUCCESS = 'snackbar/CLOSE_SNACKBAR';

export default {
  OPEN_SNACKBAR_ERROR,
  OPEN_SNACKBAR_SUCCESS,
  CLOSE_SNACKBAR_ERROR,
  CLOSE_SNACKBAR_SUCCESS,
};
